name:  Netikslumas skaidrėse
description: Pranešimas apie netikslumą skaidrėse.
title: "P__-_ (v1.0) sk._: netikslumas → taisymas (esmė)"
labels: ["Naujas :new:", "Vieta: skaidrės :orange_book:"]
body:
  - type: markdown
    attributes:
      value: |
          Temos **pavadinime** apibūdinkite netikslumo esmę, kuri padėtų **kitiems skaitytojams greitai susiorientuoti**, kad apie šį netikslumą jau pranešta.

          1. Prašykite skaidrių bloko kodą (pvz., `P01-4`);  
          2. Bloko versiją, pvz., (`v1.0`). Jei versija neparašyta, tai ji yra `1.0`.;  
          3. Skaidrės numerį, pvz. `sk.14`, per kablelį gali būti nurodytos kelios skaidrės;  
          4. Apibūdinkite netikslumo esmę. Jei galima, tokiu formatu: `netikslumas → taisymas`.
          Pvz.:  
          „`P01-4 (v1.0) sk.14: kopppiuteris → kompiuteris (rašyba)`“  
          „`P11-1 (v2.1) sk.1,5: praleistas žodis "tačiau"`“ (jei nurodytos kelios skaidrės).
  - type: checkboxes
    id: terms
    attributes:
      label: Patvirtinimas
      options:
        - label: Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
        - label: Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
          required: true
        - label: Temos pavadinime nurodžiau skaidrių bloko kodą, versiją ir skaidrės numerį.
          required: true
  - type: dropdown
    id: course
    attributes:
      label: Dalykas
      options:
        - BS-2024
        - kitas
      default: 0
    validations:
      required: true
  - type: dropdown
    id: place
    attributes:
      label: Netikslumo vieta
      options:
        - skaidrės (PDF, PowerPoint)
        - kitur
      default: 0
  - type: dropdown
    id: error-type
    attributes:
      label: Netikslumo tipas
      description: Pasirinkite vieną ar kelis.
      multiple: true
      options:
        - rašyba (praleista raidė ar kitokia rašybos klaida)
        - gramatika (nesuderinti linksniai ar kitokia gramatikos klaida)
        - praleistas žodis 
        - pasikartojimas (pasikartojantis žodis ar frazė)
        - skyryba (skyrybos klaida)
        - skaičiavimo klaida
        - fakto klaida
        - netinkamas terminas
        - stilius (stiliaus klaida)
        - kita
  - type: input
    id: error-type
    attributes:
      label: Netikslumo tipas (patikslinimas)
      description: Jei reikia, glaustai apibūdinkite ar patikslinkite netikslumo tipą
  - type: input
    id: error-with-context
    attributes:
      label: Nukopijuokite netikslumą su keliais žodžiais aplinkui
      description: To reikia greitai paieškai dokumente.
  - type: input
    id: error
    attributes:
      label: Netikslumo tekstas
    validations:
      required: true
  - type: input
    id: correction
    attributes:
      label: Siūlomas taisymo tekstas
  - type: textarea
    id: screenshot
    attributes:
      label: Ekrano nuotrauka („Screenshot“)
      description: Viena ar kelios ekrano nuotraukos su pažymėtomis netikslumų vietomis.
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: Komentaras
      description: Jei reikia, pateikite papildomos informacijos.

