name:  Papildomų balų registracija
description:  Papildomų balų registracija (kai dėstytojas juos paskiria)
title: "Papildomi balai (2024-..-..)"
labels: ["Naujas :new:", "Papildomi balai :star:"]
body:
  - type: markdown
    attributes:
      value: |
        Šią formą reikia pildyti **TIK** tada, kai paprašo dėstytojas.
  - type: dropdown
    id: course
    attributes:
      label: Dalykas
      options:
        - BS-2024
        - R-2024
        - kitas
      default: 0
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Data
      placeholder: yyyy-mm-dd
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: Už ką skirti balai?
      description: Atlikta užduotis / Atsakytas klausimas / ar pan.
    validations:
      required: true
